-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 14:26:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema users
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users` DEFAULT CHARACTER SET utf8mb3 ;
USE `users` ;

-- -----------------------------------------------------
-- Table `users`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`exercises` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `ID_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `users`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`users` (
  `Email` VARCHAR(45) NOT NULL DEFAULT 'Empty',
  `UserPassword` TEXT NULL DEFAULT NULL,
  `Forename` TEXT NULL DEFAULT NULL,
  `Surname` TEXT NULL DEFAULT NULL,
  `AccessLevel` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `users`.`exercisestats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`exercisestats` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `ExerciseName` VARCHAR(45) NOT NULL,
  `Reps` INT NOT NULL DEFAULT '0',
  `MinutesSpent` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `EmailKey_idx` (`Email` ASC) VISIBLE,
  INDEX `ExerciseKey_idx` (`ExerciseName` ASC) VISIBLE,
  CONSTRAINT `EmailKey`
    FOREIGN KEY (`Email`)
    REFERENCES `users`.`users` (`Email`),
  CONSTRAINT `ExerciseKey`
    FOREIGN KEY (`ExerciseName`)
    REFERENCES `users`.`exercises` (`Name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

INSERT INTO exercises (Name) VALUES ('Leg press');
INSERT INTO exercises (Name) VALUES ('Bench press');
INSERT INTO exercises (Name) VALUES ('Leg curl'); 
INSERT INTO exercises (Name) VALUES ('Leg extensions'); 
INSERT INTO exercises (Name) VALUES ('Chest dips'); 
INSERT INTO exercises (Name) VALUES ('Chest flies');  

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
