-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 20:43:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema computerusers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema computerusers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Users` DEFAULT CHARACTER SET utf8mb3 ;
USE `Users` ;

-- -----------------------------------------------------
-- Table `computerusers`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Users`.`users` (
  `Email` VARCHAR(45) NOT NULL DEFAULT 'Empty',
  `UserPassword` TEXT DEFAULT NULL,
  `Forename` TEXT DEFAULT NULL,
  `Surname` TEXT DEFAULT NULL,
  `AccessLevel` TEXT DEFAULT NULL,
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;